apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bonus-playground-ingress
  namespace: bonus
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bonus-playground-svc
            port:
              number: 80
