apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonus-app
  namespace: argocd
spec:
  project: bonus-app
  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc:8181/root/bonus-app.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: bonus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
