apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coisu/jischoi-Inception-of-Things-argoCD.git 
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: dev # [cite: 462]
  syncPolicy:
    automated:
      prune: true
      selfHeal: true