Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-11"

    # Severnode setting
    config.vm.define "jischoiS" do |server|
    server.vm.hostname = "jischoiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.network "forwarded_port", guest: 80, host: 8080

    server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
    end

    # K3s controller installation
    server.vm.provision "shell", inline: <<-SHELL
        echo "--- K3s server node installation started ---"
        export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --bind-address=192.168.56.110 --node-ip=192.168.56.110"
        curl -sfL https://get.k3s.io | sh -
        echo "--- K3s server node installation completed ---"
    SHELL

    # Deploy apps with script
    server.vm.provision "shell", inline: "sh /vagrant/scripts/deploy.sh"
    end
end
