# p2/Vagrantfile

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-11"

    # Severnode setting
    config.vm.define "jischoiS" do |server|
    server.vm.hostname = "jischoiS"
    server.vm.network "private_network", ip: "192.168.56.110"

    # vagrant-hostsupdater plugin manage hosts
    # config.hostsupdater.aliases = ["app1.com", "app2.com"]

    server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
    end

    # on my window pc had a problem of installing kernel
    server.vm.provision "shell", inline: <<-SHELL
      echo "--- Updating system and installing kernel headers ---"
      sudo apt-get update -y
      sudo apt-get install -y linux-headers-amd64
    SHELL

    # K3s controller installation
    server.vm.provision "shell", inline: <<-SHELL
        echo "--- K3s server node installation started ---"
        export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --bind-address=192.168.56.110 --node-ip=192.168.56.110"
        curl -sfL https://get.k3s.io | sh -
        echo "--- K3s server node installation completed ---"
    SHELL

    # Deploy apps with script
    # server.vm.provision "shell", path: "scripts/deploy.sh"
    server.vm.provision "shell", inline: "sh /vagrant/scripts/deploy.sh"
    end
end
