# p2/Vagrantfile

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-11"

    # --- 서버 노드 설정 (한 대만 정의) ---
    config.vm.define "jischoiS" do |server|
    server.vm.hostname = "jischoiS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
    end

    # K3s 컨트롤러(서버) 설치 스크립트
    server.vm.provision "shell", inline: <<-SHELL
        echo "--- K3s server node installation started ---"
        export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --bind-address=192.168.56.110 --node-ip=192.168.56.110"
        curl -sfL https://get.k3s.io | sh -
        echo "--- K3s server node installation completed ---"
    SHELL
    end
end
