# Vagrantfile

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"

  # --- SErver node ---
  config.vm.define "jischoiS" do |server|
    server.vm.hostname = "jischoiS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    server.vm.provision "shell", inline: <<-SHELL
      echo "--- K3s server node installation started ---"
      export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --bind-address=192.168.56.110 --node-ip=192.168.56.110"
      curl -sfL https://get.k3s.io | sh -
      echo "--- K3s server node installation completed ---"
      # Saving token for worker node
      cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
    SHELL
  end

  # --- Worker node ---
  config.vm.define "jischoiSW" do |worker|
    worker.vm.hostname = "jischoiSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
    
    worker.vm.provision "shell", inline: <<-SHELL
      echo "--- K3s worker node installation started ---"

      while [ ! -f /vagrant/node-token ]; do echo "Waiting for node-token..."; sleep 1; done
      export INSTALL_K3S_EXEC="--node-ip=192.168.56.111"
      export K3S_URL="https://192.168.56.110:6443"
      export K3S_TOKEN=$(cat /vagrant/node-token)
      curl -sfL https://get.k3s.io | sh -
      echo "--- K3s worker node installation completed ---"
    SHELL
  end
end
