Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = "4"
  end

# GitLab Ports
  config.vm.network "forwarded_port", guest: 80, host: 8081   # GitLab HTTP UI
  config.vm.network "forwarded_port", guest: 443, host: 8443  # GitLab HTTPS UI
# p3
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # For Argo CD UI
  config.vm.network "forwarded_port", guest: 8888, host: 8888 # For your application
  config.vm.network "forwarded_port", guest: 6443, host: 6443 # For Kubernetes API Server

  config.vm.provision "shell", inline: "sh /vagrant/scripts/bootstrap-bonus.sh"
end