Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080 # For Argo CD UI
  config.vm.network "forwarded_port", guest: 8888, host: 8888 # For your application
  config.vm.network "forwarded_port", guest: 6443, host: 6443 # For Kubernetes API Server

  config.vm.provision "shell", inline: "sh /vagrant/scripts/setup.sh"
end